version: "2"

run:
  timeout: 5m
  tests: false
  go: "1.24"
  skip-dirs:
    - tmp
  skip-files:
    - '.*_test\.go$'

linters:
  enable:
    # Default linters
    - govet
    - staticcheck
    - errcheck

    # Code quality
    - ineffassign
    - prealloc
    - nakedret
    - noctx
    - dogsled
    - bodyclose
    # omit extremely noisy duplication/complexity linters for this project
    # - dupl
    # - gocognit
    - goconst
    - gocritic
    # - gocyclo

    # Security
    - gosec

    # Documentation
    # - godot
    - godox

    # Error handling
    - errorlint

    # Misc
    - exhaustive
    - misspell
    - whitespace
    - nolintlint
    - revive

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - octalLiteral
      - commentedOutCode
      - unnamedResult
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 40
  godot:
    scope: all
    capital: true
    period: true
  # Ignore TODO notes; keep FIXME/BUG actionable findings
  godox:
    keywords:
      - FIXME
      - BUG
  dupl:
    threshold: 100
  errorlint:
    errorf: true
    errorf-multi: true
    asserts: true
    comparison: true
  exhaustive:
    check:
      - switch
      - map
    default-signifies-exhaustive: true
  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: exported
      - name: increment-decrement
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: var-declaration
      - name: var-naming

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
